services:
  backend:
    env_file: ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: yarn start:dev
