name: CD

on:
  push:
    branches:
      - main

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          passphrase: ${{ secrets.PROD_SSH_PASSPHRASE }}
          source: "."
          target: "~/personal/bento"

      - uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          passphrase: ${{ secrets.PROD_SSH_PASSPHRASE }}
          script: |
            cd ~/personal/bento
            cp ~/personal/bento/.env.backend ~/personal/bento/backend/.env
            cp ~/personal/bento/google.json ~/personal/bento/backend/secrets/google.json
            docker compose up -d --build
